version: '3'
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./databases:/var/lib/mysql/
      - ./conf/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./share:/home/share
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     MYSQL_DATABASE: anydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 80:80
    depends_on:
      - mysql
